name: ReleaseWorkflow

on:
  workflow_run:
    workflows: 
      - TestWorkflow
    types:
      - completed
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/setup-go@v3
        with: 
          go-version: '^1.19.3'
      - run: GOPROXY=proxy.golang.org go list -m github.com/bozdoz/nevermind@main
