name: TestWorkflow

on:
  push:
    tags:

jobs:
  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with: 
          go-version: '^1.19.3'
      - name: GitHub Tag Name example
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{ github.ref_name }}"
      - run: GOPROXY=proxy.golang.org go list -m github.com/bozdoz/nevermind@${{ github.ref_name }}
