name: TestWorkflow

on:
  push:
    paths-ignore:
      - "**/*.md"
      - "**/doc.go"
      - "*.sh"
      - ".gitignore"
      - "Dockerfile"
      - "LICENSE"
      - ".devcontainer/*"

jobs:
  test:
    strategy:
      matrix:
        # mac-latest too expensive
        os: ["ubuntu-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with: 
          go-version: '^1.19.3'
      - run: go test ./... -cover